<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio Memory API
 * APIs for managing memory stores, profiles, and conversational intelligence capabilities.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Twilio\Rest\Memory\V1;

use Twilio\Exceptions\TwilioException;
use Twilio\ListResource;
use Twilio\Options;
use Twilio\Values;
use Twilio\Version;
use Twilio\ApiV1Version;
use Twilio\Http\Response;
use Twilio\Metadata\ResourceMetadata;


class IdentityResolutionSettingList extends ListResource
    {
    /**
     * Construct the IdentityResolutionSettingList
     *
     * @param Version $version Version that contains the resource
     */
    public function __construct(
        Version $version
    ) {
        $apiV1Version = new ApiV1Version($version->getDomain(), $version->version);
        parent::__construct($apiV1Version);

        // Path Solution
        $this->solution = [
        ];
    }

    /**
     * Helper function for Fetch
     *
     
     * @return Response Fetched Response
     * @throws TwilioException When an HTTP error occurs.
     */
    private function _fetch(string $storeId, ): Response
    {
        
        $uri = '/ControlPlane/Stores/' . \rawurlencode($storeId)
        .'/IdentityResolutionSettings';
        
        $headers = Values::of(['Content-Type' => 'application/x-www-form-urlencoded', 'Accept' => 'application/json' ]);
        return $this->version->handleRequest('GET', $uri, [], [], $headers, "fetch");
    }

    /**
     * Fetch the IdentityResolutionSettingsInstance
     *
     
     * @return IdentityResolutionSettingsInstance Fetched IdentityResolutionSettingsInstance
     * @throws TwilioException When an HTTP error occurs.
     */
    public function fetch(string $storeId, ): IdentityResolutionSettingsInstance
    {
        $response = $this->_fetch($storeId, );
        return new IdentityResolutionSettingsInstance(
            $this->version,
            $response->getContent(),
            $storeId
        );
        
    }

    /**
     * Fetch the IdentityResolutionSettingsInstance with Metadata
     *
     
     * @return ResourceMetadata The Fetched Resource with Metadata
     * @throws TwilioException When an HTTP error occurs.
     */
    public function fetchWithMetadata(string $storeId, ): ResourceMetadata
    {
        $response = $this->_fetch($storeId, );
        $resource = new IdentityResolutionSettingsInstance(
                        $this->version,
                        $response->getContent(),
                        $storeId
                    );
        
        return new ResourceMetadata(
            $resource,
            $response->getStatusCode(),
            $response->getHeaders()
        );
    }


    /**
     * Helper function for Update
     *
     
     * @param IdentityResolutionSettingsCore $identityResolutionSettingsCore
     
     * @param array|Options $options Optional Arguments
     * @return Response Updated Response
     * @throws TwilioException When an HTTP error occurs.
     */
    private function _update(string $storeId, IdentityResolutionSettingsCore $identityResolutionSettingsCore, array $options = []): Response
    {
        
        $uri = '/ControlPlane/Stores/' . \rawurlencode($storeId)
        .'/IdentityResolutionSettings';
        
        $options = new Values($options);

        $headers = Values::of(['Content-Type' => 'application/json', 'Accept' => 'application/json' , 'If-Match' => $options['ifMatch']]);
        $data = $identityResolutionSettingsCore->toArray();
        return $this->version->handleRequest('PUT', $uri, [], $data, $headers, "update");
    }

    /**
     * Update the UpdateIdentityResolutionSettings202ResponseInstance
     *
     
     * @param IdentityResolutionSettingsCore $identityResolutionSettingsCore
     
     * @param array|Options $options Optional Arguments
     * @return UpdateIdentityResolutionSettings202ResponseInstance Updated UpdateIdentityResolutionSettings202ResponseInstance
     * @throws TwilioException When an HTTP error occurs.
     */
    public function update(string $storeId, IdentityResolutionSettingsCore $identityResolutionSettingsCore, array $options = []): UpdateIdentityResolutionSettings202ResponseInstance
    {
        $response = $this->_update($storeId,  $identityResolutionSettingsCore, $options);
        return new UpdateIdentityResolutionSettings202ResponseInstance(
            $this->version,
            $response->getContent(),
            $storeId
        );
        
    }

    /**
     * Update the UpdateIdentityResolutionSettings202ResponseInstance with Metadata
     *
     
     * @param IdentityResolutionSettingsCore $identityResolutionSettingsCore
     
     * @param array|Options $options Optional Arguments
     * @return ResourceMetadata The Updated Resource with Metadata
     * @throws TwilioException When an HTTP error occurs.
     */
    public function updateWithMetadata(string $storeId, IdentityResolutionSettingsCore $identityResolutionSettingsCore, array $options = []): ResourceMetadata
    {
        $response = $this->_update($storeId,  $identityResolutionSettingsCore, $options);
        $resource = new UpdateIdentityResolutionSettings202ResponseInstance(
                        $this->version,
                        $response->getContent(),
                        $storeId
                    );
        
        return new ResourceMetadata(
            $resource,
            $response->getStatusCode(),
            $response->getHeaders()
        );
    }


    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string
    {
        return '[Twilio.Memory.V1.IdentityResolutionSettingList]';
    }
}
