<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */

namespace Twilio\Rest\Voice\V1\ConnectionPolicy;

use Twilio\Http\Response;
use Twilio\Page;
use Twilio\Version;

class ConnectionPolicyTargetPage extends Page {
    /**
     * @param Version $version Version that contains the resource
     * @param Response $response Response from the API
     * @param array $solution The context solution
     */
    public function __construct(Version $version, Response $response, array $solution) {
        parent::__construct($version, $response);

        // Path Solution
        $this->solution = $solution;
    }

    /**
     * @param array $payload Payload response from the API
     * @return ConnectionPolicyTargetInstance \Twilio\Rest\Voice\V1\ConnectionPolicy\ConnectionPolicyTargetInstance
     */
    public function buildInstance(array $payload): ConnectionPolicyTargetInstance {
        return new ConnectionPolicyTargetInstance(
            $this->version,
            $payload,
            $this->solution['connectionPolicySid']
        );
    }

    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString(): string {
        return '[Twilio.Voice.V1.ConnectionPolicyTargetPage]';
    }
}