name: Twilio Public release-packagist

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-x64
    if: github.repository_owner == 'twilio'
    timeout-minutes: 20
    strategy:
      matrix:
        php: ['8.1', '8.3', '8.4']
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install Dependencies
        run: make install

      - name: Run Tests
        run: make test

  deploy:
    name: Publish Release
    needs: [test]
    runs-on: ubuntu-x64
    if: success() && github.ref_type == 'tag' && github.repository_owner == 'twilio'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: composer install

      - name: Get tagged version
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: sendgrid/dx-automator/actions/release@08b601b726671445abc798ed59881766ec8fefc6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
