name: Lint PR
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: Validate title
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: twilio/sdk-actions/semantic-pr-title@07f75561c932361528edeac6eeda58bd130fd74b # feat/php-composer-support @ 07f7556 (pre-release; repin to v1.1.0 tag before merge)
        with:
          types: |
            chore
            docs
            fix
            feat
            misc
            test
